name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch, may also be named 'master' or 'develop'
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      - name: Publish NuGet
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
      # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: Yust/Yust.csproj
      # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
      # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          INCLUDE_SYMBOLS: false
